export const LISTBOOKMARKS_CACHE_KEY = 'lastBookmarksList'
export const LISTTAGS_CACHE_KEY = 'lastTagsList'
export const BOOKMARK_METADATA_CACHE_KEY = 'bookmark_metadata'
export const USER_PROFILE_CACHE_KEY = 'user_profile'
export const RESET_PASSWORD_CACHE_KEY = 'reset_password'
